### ISSUE TITLE
11240 is still missing

### ISSUE THREAD

**Issue by Mercury13** [notofonts/khojki#12]
### Title 
11240 is still missing

### Font
NotoSerifKhojki-Regular.ttf

### Where the font came from, and when
Site: this repo, GH branch
Date: 2023-03-24

### Font Version
2.003

### OS name and version
All OS

### Application name and version
All apps

### Issue
No character 11240

### Character data
U+11240 Khojki letter Short I

### Screenshot
![image](https://user-images.githubusercontent.com/10164882/227480956-e06682bd-7da8-4cf2-88aa-c657b6a5d9ec.png)

**Comment by simoncozens** [comment]
We automatically generate a list of characters not currently covered in Noto fonts at
https://notofonts.github.io/overview/gaplist.txt

**Comment by Mercury13** [comment]
I’ve just noticed you’ve been working on Khojki :)

**Comment by simoncozens** [comment]
Yeah, I don't draw, I just do engineering. :-)

**Comment by Mercury13** [comment]
As a temporary thing, I’ve made this
![image](https://user-images.githubusercontent.com/10164882/227604576-afc35010-4635-4821-89a1-a9d4bad3146a.png)
IDK if it’s right.

**Comment by Mercury13** [comment]
Made from 11202.

**Comment by Mercury13** [comment]
![image](https://user-images.githubusercontent.com/10164882/227607648-fc1f4d10-0003-43eb-9af7-c4a06566756b.png)
As you see, the difference is big hook. In your Serif font big hook is united with dot, thus my design.
I don’t see exactly your design of long I in proposal of short I, but these pairs suggest I’m right.
![image](https://user-images.githubusercontent.com/10164882/227609002-314dedd7-87c7-4bd3-821a-04c9e7ef5a22.png)
![image](https://user-images.githubusercontent.com/10164882/227609124-a2bbfc84-5ea4-4ae0-9e03-56101daa12a5.png)

**Comment by Mercury13** [comment]
Concerning anchor points. There are two of them over I, 0 (anusvara and E), and 3 (nukta/shadda/sukun). Only anusvara can theoretically hang above vowel, so place this anchor into some feasible position.

**Comment by Mercury13** [comment]
2 is U/R/virama (cannot hang under vowel), and 1 is rakar (cannot either).

**Comment by Mercury13** [comment]
Probably I should have drawn something like this
![image](https://user-images.githubusercontent.com/10164882/227617245-81a47055-cf5d-43d0-a3fd-bd77fca542ae.png)

**Comment by Mercury13** [comment]
Probably I should have drawn something like this
![image](https://user-images.githubusercontent.com/10164882/227617512-93e6e016-541e-404d-8fb5-83d5da1714eb.png)
