### ISSUE TITLE
Inaccessible glyphs in Noto Serif Khojki

### ISSUE THREAD

**Issue by dscorbett** [notofonts/khojki#19]
### Font
NotoSerifKhojki-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/khojki/releases/tag/NotoSerifKhojki-v2.004
Date: 2023-06-25

### Font version
Version 2.004

### Issue
Some glyphs are inaccessible:
* `Nukta_aiMatrakhoj`
* `Nukta_auMatrakhoj`
* `Nukta_eMatrakhoj`
* `Nukta_oMatrakhoj`
* `q_ra_uMatrakhoj`
* `rakar_rVocalicMatra`
* `sh_ra_iMatrakhoj`
* `sh_ra_iiMatrakhoj`
* `sh_ra_uMatrakhoj`

### Character data
𑈔𑈶𑈱
U+11214 KHOJKI LETTER TTA
U+11236 KHOJKI SIGN NUKTA
U+11231 KHOJKI VOWEL SIGN AI
𑈔𑈶𑈳
U+11214 KHOJKI LETTER TTA
U+11236 KHOJKI SIGN NUKTA
U+11233 KHOJKI VOWEL SIGN AU
𑈔𑈶𑈰
U+11214 KHOJKI LETTER TTA
U+11236 KHOJKI SIGN NUKTA
U+11230 KHOJKI VOWEL SIGN E
𑈔𑈶𑈲
U+11214 KHOJKI LETTER TTA
U+11236 KHOJKI SIGN NUKTA
U+11232 KHOJKI VOWEL SIGN O
𑈿𑈵𑈦𑈯
U+1123F KHOJKI LETTER QA
U+11235 KHOJKI SIGN VIRAMA
U+11226 KHOJKI LETTER RA
U+1122F KHOJKI VOWEL SIGN U
𑈔𑈵𑈦𑉁
U+11214 KHOJKI LETTER TTA
U+11235 KHOJKI SIGN VIRAMA
U+11226 KHOJKI LETTER RA
U+11241 KHOJKI VOWEL SIGN VOCALIC R
𑈩𑈶𑈵𑈦𑈭
U+11229 KHOJKI LETTER SA
U+11236 KHOJKI SIGN NUKTA
U+11235 KHOJKI SIGN VIRAMA
U+11226 KHOJKI LETTER RA
U+1122D KHOJKI VOWEL SIGN I
𑈩𑈶𑈵𑈦𑈮
U+11229 KHOJKI LETTER SA
U+11236 KHOJKI SIGN NUKTA
U+11235 KHOJKI SIGN VIRAMA
U+11226 KHOJKI LETTER RA
U+1122E KHOJKI VOWEL SIGN II
𑈩𑈶𑈵𑈦𑈯
U+11229 KHOJKI LETTER SA
U+11236 KHOJKI SIGN NUKTA
U+11235 KHOJKI SIGN VIRAMA
U+11226 KHOJKI LETTER RA
U+1122F KHOJKI VOWEL SIGN U

### Screenshot
![𑈔𑈶𑈱𑈔𑈶𑈳𑈔𑈶𑈰𑈔𑈶𑈲𑈿𑈵𑈦𑈯𑈔𑈵𑈦𑉁𑈩𑈶𑈵𑈦𑈭𑈩𑈶𑈵𑈦𑈮𑈩𑈶𑈵𑈦𑈯](https://github.com/notofonts/khojki/assets/1124347/dd1aabef-c66b-4cee-b4fb-d65df15c2aa4)

**Comment by simoncozens** [comment]
The first four went away now we are using mkmk; I fixed the others.

**Comment by simoncozens** [comment]
The first four went away now we are using mkmk; I fixed the others.
