### ISSUE TITLE
Below-base ra blocks post-base ya in Noto Serif Khojki

### ISSUE THREAD

**Issue by dscorbett** [notofonts/khojki#20]
### Font
NotoSerifKhojki-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/khojki/releases/tag/NotoSerifKhojki-v2.004
Date: 2023-06-25

### Font version
Version 2.004

### Issue
Post-base <i>ya</i> is not formed after below-base <i>ra</i>, except in syllables like <i>khrya</i> where the base ligates with the <i>ra</i>. Post-base <i>ya</i> should be formed either way.

### Character data
𑈈𑈵𑈦𑈵𑈥𑈉𑈵𑈦𑈵𑈥
U+11208 KHOJKI LETTER KA
U+11235 KHOJKI SIGN VIRAMA
U+11226 KHOJKI LETTER RA
U+11235 KHOJKI SIGN VIRAMA
U+11225 KHOJKI LETTER YA
U+11209 KHOJKI LETTER KHA
U+11235 KHOJKI SIGN VIRAMA
U+11226 KHOJKI LETTER RA
U+11235 KHOJKI SIGN VIRAMA
U+11225 KHOJKI LETTER YA

### Screenshot
![𑈈𑈵𑈦𑈵𑈥𑈉𑈵𑈦𑈵𑈥](https://github.com/notofonts/khojki/assets/1124347/90ba1df8-6c1a-4410-9573-459c46ff2b82)

**Comment by simoncozens** [comment]
This seems to have worked itself out in recent changes:

![shape](https://github.com/notofonts/khojki/assets/106728/987f1f2a-fb64-481d-b165-846a3dca9caa)
