### ISSUE TITLE
Sans: 11241 is missing

### ISSUE THREAD

**Issue by aelatham** [notofonts/khojki#28]
U+11241 is missing in Noto Sans Khojki. I would like to see both fonts have full support for this block so that you can choose which font to pick.
![Screenshot 2024-03-30 223642](https://github.com/notofonts/khojki/assets/165534177/82836b4e-1f8a-42e0-bbab-ba9c9a4885b8)

**Comment by simoncozens** [comment]
Fixed in #29.
