### ISSUE TITLE
U+1123E KHOJKI SIGN SUKUN overlaps marks above

### ISSUE THREAD

**Issue by dscorbett** [notofonts/khojki#7]
### Fonts
NotoSansKhojki-Regular.otf
NotoSerifKhojki-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/khojki/releases/tag/NotoSansKhojki-v2.002
Site: https://github.com/notofonts/khojki/releases/tag/NotoSerifKhojki-v2.002
Date: 2022-08-30

### Font version
Version 2.002

### Issue
U+1123E KHOJKI SIGN SUKUN overlaps marks above.

### Character data
𑈈𑈱𑈾
U+11208 KHOJKI LETTER KA
U+11231 KHOJKI VOWEL SIGN AI
U+1123E KHOJKI SIGN SUKUN

### Screenshots
![𑈈𑈱𑈾](https://user-images.githubusercontent.com/1124347/187462041-8c7b77c1-b74d-406e-a6fb-1b356e511886.png)
![𑈈𑈱𑈾](https://user-images.githubusercontent.com/1124347/187462783-b707cea4-44e4-43f6-ade0-e2c710c4bf62.png)

**Comment by simoncozens** [comment]
There are various overlapping mark problems; shadda/nukta being another one in both sans and serif, with and without a dependent vowel in the way.
